/** Chinese display labels only. Supplier names and codes remain unchanged for requests/search. */
const normalizeName = (name: string) => name.trim().normalize('NFKD').replace(/\p{Diacritic}/gu, '').toLocaleLowerCase('en-US').replace(/[’‘]/g, "'").replace(/\s+/g, ' ');

const placeTranslations: Record<string, string> = {
  'Alice Springs': '爱丽丝泉',
  'Ballarat': '巴拉瑞特',
  'Brisbane': '布里斯班',
  'Cairns': '凯恩斯',
  'Canberra': '堪培拉',
  'Darwin': '达尔文',
  'Gold Coast': '黄金海岸',
  'Hobart': '霍巴特',
  'Kangaroo Island': '袋鼠岛',
  'Blue Mountains': '蓝山',
  'Launceston': '朗塞斯顿',
  'Lithgow City': '利斯戈',
  'Mareeba': '马里巴',
  'Melbourne': '墨尔本',
  'Murray Bridge': '默里布里奇',
  'Perth': '珀斯',
  'Port Stephens': '史蒂芬斯港',
  'Colac Otway': '科拉克奥特韦',
  'Corangamite': '科兰加迈特',
  'Sunshine Coast': '阳光海岸',
  'Sydney': '悉尼',
  'Warrnambool': '瓦南布尔',
  'Yulara': '尤拉拉',
  'Bezirk Melk': '梅尔克区',
  'Gmunden': '格蒙登',
  'Vienna': '维也纳',
  'Beijing': '北京',
  'Chengde City': '承德',
  'Chengdu': '成都',
  'Chongqing': '重庆',
  'Foshan City': '佛山',
  'Gannan Tibetan Autonomous Prefecture': '甘南藏族自治州',
  'Garze': '甘孜藏族自治州',
  'Guangzhou City': '广州',
  'Guiyang': '贵阳',
  'Haixi Mongol and Tibetan Autonomous Prefecture': '海西蒙古族藏族自治州',
  'Hangzhou': '杭州',
  'Kashgar': '喀什',
  'Kunming': '昆明',
  'Ngawa': '阿坝藏族羌族自治州',
  'Qingyuan City': '清远',
  'Sanya City': '三亚',
  'Shanghai': '上海',
  'Shenzhen City': '深圳',
  'Suzhou City': '苏州',
  'Tianjin': '天津',
  'Xishuangbanna': '西双版纳',
  'Zhangjiajie': '张家界',
  'Zhangye': '张掖',
  'Zhongshan': '中山',
  'Zhongwei': '中卫',
  'Zhuhai': '珠海',
  'Urumqi': '乌鲁木齐',
  'Cairo': '开罗',
  'Giza': '吉萨',
  'Hurghada': '赫尔格达',
  'Sharm El Sheikh': '沙姆沙伊赫',
  'Agen': '阿让',
  'Avignon': '阿维尼翁',
  'Avranches': '阿夫朗什',
  'Bayeux': '巴约',
  'Beaune': '博讷',
  'Blois': '布卢瓦',
  'Carcassonne': '卡尔卡松',
  'Fontainebleau': '枫丹白露',
  'Les Andelys': '莱桑德利',
  'Marseille': '马赛',
  'Paris': '巴黎',
  'Reims': '兰斯',
  'Saint-Germain-en-Laye': '圣日耳曼昂莱',
  'Torcy': '托尔西',
  'Tours': '图尔',
  'Versailles': '凡尔赛',
  'Batumi': '巴统',
  'Gori Municipality': '哥里市',
  'Kazbegi Municipality': '卡兹别吉市',
  'Mtskheta': '姆茨赫塔',
  'Sagarejo Municipality': '萨加雷焦市',
  'Sighnaghi': '西格纳吉',
  'Tbilisi': '第比利斯',
  'Ansbach (district)': '安斯巴赫县',
  'Berlin': '柏林',
  'Konstanz': '康斯坦茨',
  'Cologne': '科隆',
  'Landkreis Dachau': '达豪县',
  'Landkreis Ostallgäu': '东阿尔高县',
  'Munich': '慕尼黑',
  'Hong Kong': '香港',
  'Bláskógabyggð': '布劳斯科加比格兹',
  'Eyja- og Miklaholtshreppur': '埃亚米克拉霍尔茨区',
  'Grindavik': '格林达维克',
  'Norðurþing': '诺尔杜廷',
  'Reykjavik': '雷克雅未克',
  'Sveitarfélagið Hornafjörður': '霍尔纳菲厄泽市',
  'Abiansemal': '阿比安塞马尔',
  'Bangli Regency': '邦利县',
  'Batu': '巴图',
  'Blahbatuh': '布拉巴图',
  'Buleleng': '布勒冷',
  'Denpasar': '登巴萨',
  'Gerokgak': '格罗加克',
  'Gianyar': '吉安雅',
  'Gianyar Regency': '吉安雅县',
  'Jakarta': '雅加达',
  'Central Lombok': '中龙目县',
  'Karangasem Regency': '卡朗阿森县',
  'Kuta': '库塔',
  'South Kuta': '南库塔',
  'Kuta Utara': '北库塔',
  'Magelang Regency': '马格朗县',
  'Mengwi': '孟威',
  'Pasuruan Regency': '巴苏鲁安县',
  'Payangan': '帕扬安',
  'Penebel': '佩内贝尔',
  'Sleman Regency': '斯勒曼县',
  'Sukawati': '苏卡瓦蒂',
  'Tangerang': '唐格朗',
  'Tegallalang': '德格拉朗',
  'Ubud': '乌布',
  'West Bandung Regency': '西万隆县',
  'Amalfi': '阿马尔菲',
  'Bagnoregio': '白露里治奥',
  'Bronte': '布龙泰',
  'Capri': '卡普里',
  'Cernobbio': '切尔诺比奥',
  "Cortina d'Ampezzo": '科尔蒂纳丹佩佐',
  'Florence': '佛罗伦萨',
  'Menaggio': '梅纳焦',
  'Milan': '米兰',
  'Naples': '那不勒斯',
  'Palermo': '巴勒莫',
  'Pisa': '比萨',
  'Pompei': '庞贝',
  'Positano': '波西塔诺',
  'Ravenna': '拉文纳',
  'Rocca Pietore': '罗卡皮耶托雷',
  'Rome': '罗马',
  'Scandicci': '斯坎迪奇',
  'Siena': '锡耶纳',
  'Turin': '都灵',
  "Unione Terre d'Acqua": '泰雷达夸市镇联合区',
  'Unione dei comuni del Distretto Ceramico': '陶瓷区市镇联合区',
  'Venice': '威尼斯',
  'Verona': '维罗纳',
  'Abuta': '虻田郡',
  'Amakusa': '天草',
  'Asahikawa': '旭川',
  'Ashigarashimo': '足柄下郡',
  'Atami': '热海',
  'Chitose': '千岁',
  'Fujinomiya': '富士宫',
  'Fujisawa': '藤泽',
  'Fukuoka': '福冈',
  'Furano': '富良野',
  'Ginowan': '宜野湾',
  'Gujo': '郡上',
  'Hakodate': '函馆',
  'Higashi-osaka': '东大阪',
  'Himeji': '姬路',
  'Hiroshima': '广岛',
  'Ichinoseki': '一关',
  'Ishigaki': '石垣',
  'Ishikari': '石狩',
  'Ito County': '伊都郡',
  'Ito': '伊东',
  'Kamakura': '镰仓',
  'Kameoka': '龟冈',
  'Kamiamakusa': '上天草',
  'Kanazawa': '金泽',
  'Kitasaku': '北佐久郡',
  'Kumage County': '熊毛郡',
  'Kunigami': '国头郡',
  'Kyoto': '京都',
  'Matsumoto': '松本',
  'Minamiawaji': '南淡路',
  'Minamitsuru': '南都留郡',
  'Mino': '箕面',
  'Miyakojima': '宫古岛',
  'Miyazu': '宫津',
  'Nago': '名护',
  'Nagoya': '名古屋',
  'Naha': '那霸',
  'Nakagami': '中头郡',
  'Nakaniikawa': '中新川郡',
  'Nakatsugawa': '中津川',
  'Nanjo': '南城',
  'Nanto': '南砺',
  'Nara': '奈良',
  'Narita': '成田',
  'Nikko': '日光',
  'Nishiumuro County': '西牟娄郡',
  'Nishiusuki County': '西臼杵郡',
  'Noboribetsu': '登别',
  'Obanazawa': '尾花泽',
  'Odawara': '小田原',
  'Okayama': '冈山',
  'Ono District': '大野郡',
  'Osaka': '大阪',
  'Sapporo': '札幌',
  'Sasebo': '佐世保',
  'Sennan County': '泉南郡',
  'Shakotan': '积丹',
  'Shimajiri': '岛尻郡',
  'Shimoda': '下田',
  'Shizuoka': '静冈',
  'Suita': '吹田',
  'Tokyo': '东京',
  'Usu': '有珠郡',
  'Wakayama': '和歌山',
  'Yaeyama': '八重山郡',
  'Yokohama': '横滨',
  'Otsu': '大津',
  'Macau': '澳门',
  'Air Itam': '亚依淡',
  'Barat Daya': '西南县',
  'Bentong': '文冬',
  'Besut': '勿述',
  'Cameron Highlands': '金马仑高原',
  'George Town': '乔治市',
  'Gombak': '鹅唛',
  'Hulu Langat': '乌鲁冷岳',
  'Iskandar Puteri': '依斯干达公主城',
  'Johor Bahru': '新山',
  'Kampar': '金宝',
  'Kinta': '近打',
  'Kota Belud': '哥打毛律',
  'Kota Kinabalu': '亚庇',
  'Kota Tinggi': '哥打丁宜',
  'Langkawi': '兰卡威',
  'Kuala Langat': '瓜拉冷岳',
  'Kuala Lumpur': '吉隆坡',
  'Kuala Selangor': '瓜拉雪兰莪',
  'Kuantan': '关丹',
  'Kulai': '古来',
  'Malacca City': '马六甲',
  'Petaling Jaya': '八打灵再也',
  'Rembau': '林茂',
  'Seberang Perai': '威省',
  'Semporna': '仙本那',
  'Sepang': '雪邦',
  'Shah Alam': '莎阿南',
  'Timur Laut': '东北县',
  'Tuaran': '斗亚兰',
  'Amsterdam': '阿姆斯特丹',
  'Lisse': '利瑟',
  'Rotterdam': '鹿特丹',
  'Steenwijkerland': '斯滕韦克兰',
  'Zaanstad': '赞斯塔德',
  'Auckland': '奥克兰',
  'Bay of Islands': '岛屿湾',
  'Christchurch': '基督城',
  'Cromwell': '克伦威尔',
  'Hanmer Springs': '汉默温泉',
  'Kaikoura': '凯库拉',
  'Lake Tekapo': '蒂卡波湖',
  'Matamata': '玛塔玛塔',
  'Queenstown': '皇后镇',
  'Rolleston': '罗尔斯顿',
  'Rotorua District': '罗托鲁瓦区',
  'Southland': '南地',
  'Southland District': '南地区',
  'Taupo': '陶波',
  'Wanaka': '瓦纳卡',
  'Westport': '韦斯特波特',
  'Cebu City': '宿务',
  'Dauis': '道伊斯',
  'Lapu-Lapu': '拉普拉普',
  'Loboc': '罗博',
  'Malay': '马莱',
  'Manila': '马尼拉',
  'Panglao': '邦劳',
  'Paranaque': '帕拉尼亚克',
  'Pasay': '帕赛',
  'Pasig': '帕西格',
  'Puerto Princesa': '公主港',
  'Rodriguez': '罗德里格斯',
  'San Juan': '圣胡安',
  'Tagbilaran': '塔比拉兰',
  'Taguig': '达义',
  'Singapore': '新加坡',
  'Busan': '釜山',
  'Daegu': '大邱',
  'Gangwon-do': '江原道',
  'Gyeongju': '庆州',
  'Jeju': '济州',
  'Seogwipo': '西归浦',
  'Seoul': '首尔',
  'Adeje': '阿德赫',
  'Baix Llobregat': '下略布雷加特',
  'Barcelona': '巴塞罗那',
  'Granada': '格拉纳达',
  'Madrid': '马德里',
  'Palma': '帕尔马',
  'Puerto de la Cruz': '克鲁斯港',
  'Segovia': '塞哥维亚',
  'Selva': '塞尔瓦',
  'Seville': '塞维利亚',
  'Valencia': '瓦伦西亚',
  'Yaiza': '亚伊萨',
  'Alpnach': '阿尔普纳赫',
  'Engelberg': '英格堡',
  'Geneva': '日内瓦',
  'Kilchberg (ZH)': '基尔希贝格',
  'Laufen-Uhwiesen': '劳芬乌维森',
  'Lucerne': '卢塞恩',
  'Zurich': '苏黎世',
  'Bang Lamung': '邦拉蒙',
  'Bangkok': '曼谷',
  'Chiang Mai': '清迈',
  'Chiang Mai Province': '清迈府',
  'Chiang Rai Province': '清莱府',
  'Chom Thong': '宗通',
  'Chonburi': '春武里',
  'Doi Saket': '堆沙革',
  'Hang Dong': '杭东',
  'Kanchanaburi Province': '北碧府',
  'Ko Lan': '格兰岛',
  'Ko Samui': '苏梅岛',
  'Krabi Province': '甲米府',
  'Mae Chaem': '湄占',
  'Mae Rim': '湄林',
  'Mae Taeng': '湄登',
  'Mae Wang': '湄旺',
  'Mueang Chiang Mai': '清迈市',
  'Pak Chong': '巴冲',
  'Pattaya': '芭堤雅',
  'Phang Nga': '攀牙',
  'Phra Nakhon Si Ayutthaya Province': '大城府',
  'Phuket Province': '普吉府',
  'Ratchaburi Province': '叻丕府',
  'Sam Roi Yot': '三百峰',
  'Samut Sakhon Province': '龙仔厝府',
  'Samut Songkhram Province': '夜功府',
  'San Kamphaeng': '山甘烹',
  'San Sai': '讪赛',
  'Saraphi': '沙拉披',
  'Sattahip': '梭桃邑',
  'Si Racha': '是拉差',
  'Takua Pa': '达瓜巴',
  'Takua Thung': '达瓜通',
  'Thai Mueang': '泰孟',
  'Sakarya': '萨卡里亚',
  'Antalya': '安塔利亚',
  'Bursa': '布尔萨',
  'Central Anatolia Region': '中安纳托利亚',
  'Denizli': '代尼兹利',
  'Istanbul': '伊斯坦布尔',
  'Karaman': '卡拉曼',
  'Muğla': '穆拉',
  'Nevşehir': '内夫谢希尔',
  'Selçuk': '塞尔丘克',
  'Çanakkale': '恰纳卡莱',
  'Abu Dhabi': '阿布扎比',
  'Dubai': '迪拜',
  'Ras Al Khaimah': '哈伊马角',
  'Sharjah': '沙迦',
  'Amesbury': '埃姆斯伯里',
  'Belfast': '贝尔法斯特',
  'Brighton and Hove': '布莱顿霍夫',
  'Cambridge': '剑桥',
  'Canterbury': '坎特伯雷',
  'Cherwell': '彻韦尔',
  'Edinburgh': '爱丁堡',
  'Cotswold': '科茨沃尔德',
  'Cumbria': '坎布里亚',
  'Inverness': '因弗内斯',
  'Liverpool': '利物浦',
  'London': '伦敦',
  'Oxford': '牛津',
  'West Oxfordshire': '西牛津郡',
  'Windsor and Maidenhead': '温莎梅登黑德',
  'York': '约克',
  'Anaheim': '阿纳海姆',
  'Atlanta': '亚特兰大',
  'Atlantic City': '大西洋城',
  'Austin': '奥斯汀',
  'Bay Lake': '贝湖',
  'Boston': '波士顿',
  'Carlsbad': '卡尔斯巴德',
  'Chicago': '芝加哥',
  'Dallas': '达拉斯',
  'Denver': '丹佛',
  'Garden Ridge': '加登里奇',
  'Gatlinburg': '盖特林堡',
  'Grand Canyon Village': '大峡谷村',
  'Island of Hawaii': '夏威夷岛',
  'Honolulu': '檀香山',
  'Houston': '休斯敦',
  'Las Vegas': '拉斯维加斯',
  'Los Angeles': '洛杉矶',
  'Mariposa': '马里波萨',
  'Maui County': '茂宜县',
  'Miami': '迈阿密',
  'Mohave County': '莫哈维县',
  'Nashville': '纳什维尔',
  'Jersey City': '泽西市',
  'New Orleans': '新奥尔良',
  'New York': '纽约',
  'Niagara Falls': '尼亚加拉瀑布',
  'Orange County': '橙县',
  'Orlando': '奥兰多',
  'Pacific Grove': '太平洋丛林',
  'Page': '佩奇',
  'Palm Springs': '棕榈泉',
  'Philadelphia': '费城',
  'Phoenix': '凤凰城',
  'San Antonio': '圣安东尼奥',
  'San Diego': '圣迭戈',
  'San Francisco': '旧金山',
  'Seattle': '西雅图',
  'St. Louis': '圣路易斯',
  'St. Petersburg': '圣彼得斯堡',
  'Tampa': '坦帕',
  'Washington DC': '华盛顿哥伦比亚特区',
  'West Hollywood': '西好莱坞',
  'Yorba Linda': '约巴林达',
  'Vatican City': '梵蒂冈',
  'Bien Hoa City': '边和',
  'Buon Ma Thuot': '邦美蜀',
  'Bắc Bình District': '北平县',
  'Bến Tre City': '槟椥',
  'Cát Hải District': '吉海县',
  'Cù Lao Dung District': '岣崂榕县',
  'Da Nang': '岘港',
  'Dien Ban District': '奠盘',
  'Duy Xuyen': '维川县',
  'Go Cong Dong District': '鹅贡东县',
  'Hanoi': '河内',
  'Ho Chi Minh City': '胡志明市',
  'Hoa Lu': '华闾',
  'Hoi An': '会安',
  'Hue City': '顺化',
  'Hàm Thuận Nam District': '咸顺南县',
  'Ha Long City': '下龙',
  'Kien Giang': '坚江',
  'Lac Duong': '乐阳县',
  'My Tho': '美湫',
  'Nha Trang': '芽庄',
  'Ninh Binh': '宁平',
  'Phan Thiet': '潘切',
  'Phu Loc District': '富禄县',
  'Phu Quoc District': '富国岛',
  'Sapa': '沙坝',
  'Tam Duong': '三堂县',
  'Tam Ky': '三岐',
  'Thang Binh': '升平县',
  'Vung Tau': '头顿',
  'Da Lat': '大叻',
  "Đăk R'Lấp District": '得热勒县',
  // Additional supplier labels found by auditing all 3,114 catalog products.
  'Akaroa': '阿卡罗阿',
  'Al Batayih': '巴塔伊赫',
  'Alexandria': '亚历山大',
  'Altay Prefecture': '阿勒泰地区',
  'Ardgour': '阿德戈尔',
  'Arrondissement of Bordeaux': '波尔多区',
  'Avanos': '阿瓦诺斯',
  'Bass Coast': '巴斯海岸',
  'Buleleng Regency': '布勒冷县',
  'Byron': '拜伦',
  'Cessnock City': '塞斯诺克',
  'Cheorwon': '铁原',
  'Christchurch District': '基督城区',
  'Chuncheon': '春川',
  'City of Adelaide': '阿德莱德',
  'Como': '科莫',
  'Dandaragan': '丹达拉根',
  'District de Lausanne': '洛桑区',
  'Douglas': '道格拉斯',
  'Dusheti Municipality': '杜舍蒂市',
  'East Rutherford': '东卢瑟福',
  'Eurobodalla Shire': '尤罗博达拉郡',
  'Fiordland': '峡湾地区',
  'Fox Glacier': '福克斯冰川',
  'Franz Josef': '弗朗兹约瑟夫',
  'Gapyeong': '加平',
  'Glamorgan-Spring Bay': '格拉摩根斯普林湾',
  'Goyang': '高阳',
  'Guangzhou': '广州',
  'Guidonia Montecelio': '圭多尼亚蒙泰切廖',
  'Gwacheon-si': '果川',
  'Ha Long': '下龙',
  'Ho Chi Minh': '胡志明市',
  'Interlaken-Oberhasli': '因特拉肯上哈斯利区',
  'Kamikawa (Ishikari) District': '上川郡（石狩）',
  'Karatay': '卡拉泰',
  'Kathu': '卡图',
  'Kediri': '克迪里',
  'Kemer': '凯梅尔',
  'Kentish': '肯蒂什',
  'Kingborough': '金伯勒',
  'Komodo': '科莫多',
  'Krabi': '甲米',
  'Kumluca': '库姆卢贾',
  'Le Léman (VD)': '莱芒湖地区',
  'Lori Province': '洛里省',
  'Macdonnell': '麦克唐奈',
  'Merritt Island': '梅里特岛',
  'Miami Beach': '迈阿密海滩',
  'Miami-Dade County': '迈阿密戴德县',
  'Mount Samson': '萨姆森山',
  'Málaga-Costa del Sol': '马拉加太阳海岸',
  'Nevsehir District': '内夫谢希尔区',
  'Ngongotahā': '恩贡戈塔哈',
  'North Lombok': '北龙目县',
  'Northampton': '北安普敦',
  'Nusa Penida': '佩尼达岛',
  'Oljato-Monument Valley': '奥尔贾托纪念碑谷',
  'Osceola County': '奥西奥拉县',
  'Paju': '坡州',
  'Pastoral Unincorporated Area': '牧区非建制地区',
  'Phu Quoc': '富国岛',
  'Phuket City': '普吉市',
  'Rotorua': '罗托鲁瓦',
  'Salem': '塞勒姆',
  'San Lorenzo de El Escorial': '圣洛伦索德埃尔埃斯科里亚尔',
  'Schwyz': '施维茨',
  'Scituate': '锡楚埃特',
  'Shari': '斜里',
  'Shenzhen': '深圳',
  'Shoalhaven': '肖尔黑文',
  'Sokcho': '束草',
  'Somerville': '萨默维尔',
  'Stratford-on-Avon': '埃文河畔斯特拉特福',
  'Subang Jaya': '梳邦再也',
  'Tarragonès': '塔拉戈内斯',
  'Tasman': '塔斯曼',
  'Thalang': '他朗',
  'Three Rivers': '三河区',
  'Town of Goshen': '戈申镇',
  'Town/Village of Harrison': '哈里森镇',
  'Tweed Shire': '特威德郡',
  'Vega de Granada': '格拉纳达平原',
  'Visp': '菲斯普',
  'Wainui': '怀努伊',
  'Wat Pradu': '瓦普拉杜',
  'West Lombok': '西龙目县',
  'Weston': '韦斯顿',
  'Whitsunday Region': '圣灵群岛地区',
  'Woodwalk Landing': '伍德沃克兰丁',
  'Yongin': '龙仁',
};

const countryRegions: Record<string, string> = {
  'Armenia': 'AM', 'Australia': 'AU', 'Austria': 'AT', 'Mainland China': 'CN',
  'China': 'CN', 'Egypt': 'EG', 'France': 'FR', 'Georgia': 'GE', 'Germany': 'DE',
  'Hong Kong': 'HK', 'Iceland': 'IS', 'Indonesia': 'ID', 'Italy': 'IT', 'Japan': 'JP',
  'Macau': 'MO', 'Macao': 'MO', 'Malaysia': 'MY', 'Netherlands': 'NL', 'New Zealand': 'NZ',
  'Philippines': 'PH', 'Singapore': 'SG', 'South Korea': 'KR', 'Korea': 'KR',
  'Spain': 'ES', 'Switzerland': 'CH', 'Thailand': 'TH', 'Turkey': 'TR', 'Türkiye': 'TR',
  'United Arab Emirates': 'AE', 'United Kingdom': 'GB', 'United States': 'US',
  'Vatican City': 'VA', 'Vietnam': 'VN', 'Taiwan': 'TW',
};

const categoryTranslations: Record<string, string> = {
  'Cruise': '邮轮',
  'Cruise_TTD': '邮轮体验',
  'In-city Transportation Pass': '市内交通通票',
  'In-city _transportation_Pass (Abandoned)': '市内交通通票',
  'Railway Pass': '铁路通票',
  'Japan Railway Pass': '日本铁路通票',
  'Other Pass (Rail/ Bus)': '其他铁路及巴士通票',
  'Recurring Shows': '演出娱乐',
  'Shows & Musicals': '表演与音乐剧',
  'Sports': '体育赛事',
  'eSIM / 电话卡': '电子电话卡与电话卡',
  'eSIM': '电子电话卡',
  'Theme park': '主题乐园',
  'Theme Parks': '主题乐园',
  'Water Parks': '水上乐园',
  '休闲室': '机场贵宾室',
  'Airport Lounge': '机场贵宾室',
  '公共交通（非API）': '公共交通',
  'Attraction Public Transfer (Abandoned)': '景点交通',
  'Bus_TTD': '巴士',
  'Ferries_TTD': '渡轮',
  'Intercity Public Transfer (Abandoned)': '城际交通',
  'Train_TTD': '火车',
  'ATV & All Wheel Drive': '全地形车与越野车',
  'Abandoned(too)': '其他体验',
  'Animal Watching & Interaction': '动物观赏与互动',
  'Beach/Resort Pass': '海滩及度假村通票',
  'Beverage Tastings': '饮品品鉴',
  'Biking & Segway & Scooter': '骑行与平衡车体验',
  'Boats & Yachts & Catamarans': '游船与游艇',
  'Bungee': '蹦极',
  'Camping & Glamping': '露营与豪华露营',
  'Canyoning': '溪降',
  'Climbing': '攀岩',
  'Cooking Classes': '烹饪课程',
  'Costume & Attire': '服饰体验',
  'Dining Experiences': '餐饮体验',
  'Diving & Snorkeling': '潜水与浮潜',
  'Elephant Sanctuary': '大象保护区',
  'Fishing & Catching': '垂钓与捕捞',
  'Fitness & Sports': '健身与运动',
  'Flight & Helicopter': '飞行与直升机体验',
  'Gliding': '滑翔',
  'Go Karting & Racing': '卡丁车与赛车',
  'Hanbok': '韩服体验',
  'Hot Air Ballon': '热气球',
  'Hot Air Balloon': '热气球',
  'Hot Spring': '温泉',
  'Indoor Games': '室内游戏',
  'Kimono': '和服体验',
  'Lessons & Workshops': '课程与工作坊',
  'Muay Thai': '泰拳',
  'Nightlife & Pub Crawls': '夜生活与酒吧巡游',
  'Other Aerial Activities': '其他空中体验',
  'Other Water Sports': '其他水上运动',
  'Outlet tour': '奥特莱斯购物游',
  'PADI Diving': '潜水认证课程',
  'Paddleboading': '桨板',
  'Paddleboarding': '桨板',
  'Photography': '摄影体验',
  'Rafting': '漂流',
  'Samurai & Ninja': '武士与忍者体验',
  'Sightseeing Cruise': '观光游船',
  'Skiing & Snow Sports': '滑雪与雪上运动',
  'Skydiving': '跳伞',
  'Sumo': '相扑',
  'Surfing': '冲浪',
  'Wellness & Health': '康养与健康',
  'Zip-line': '高空滑索',
  'Abandoned': '其他体验',
  'Ancient Ruins': '古迹遗址',
  'Aquariums': '水族馆',
  'Attractions Pass': '景点通票',
  'Cable Car & Gondola & Skywheels': '缆车与摩天轮',
  'Castles & Palaces': '城堡与宫殿',
  'Cathedral & Churches': '大教堂与教堂',
  'Farms': '农场',
  'Gardens & Parks': '花园与公园',
  'Hop On Hop Off Bus': '随上随下观光巴士',
  'Museums & Galleries': '博物馆与美术馆',
  'Natural Landscape': '自然景观',
  'Observation Decks & Towers': '观景台与高塔',
  'Playgrounds': '游乐场',
  'Temples & Shrines': '寺庙与神社',
  'Villages': '村落',
  'Zoos & Animal Parks': '动物园与野生动物园',
  '水疗 & 美容': '水疗与美容',
  'Salon & Beauty': '美发与美容',
  'Spa & Massage': '水疗与按摩',
  'ATV & All Wheel Drive Tour': '全地形车与越野车之旅',
  'Air Tour': '空中观光',
  'Bicycle Tours': '自行车观光',
  'Boat Tours': '游船观光',
  'Bus Tour': '巴士观光',
  'Car Tour': '汽车观光',
  'Cruise Tour': '邮轮之旅',
  'Food & Drinks Tour': '美食与饮品之旅',
  'Hiking & Trekking Tour': '徒步之旅',
  'Hop On Hop Off Bus (Abandoned)': '随上随下观光巴士',
  'Kayaking Tour': '皮划艇之旅',
  'Motorcycle & Scooter & Segway Tour': '摩托车与平衡车观光',
  'Multiday Tour': '多日游',
  'Outlet tours': '奥特莱斯购物游',
  'Railway Tour': '铁路观光',
  'Walking Tour': '步行观光',
  '租借 - 非API': '租赁服务',
  'Charter by Itinerary': '行程包车',
  'Customized Charter': '定制包车',
  'Shopping x Discount Coupon': '购物优惠券',
  'Shopping x Gift Card & Cash Voucher': '购物礼品卡与代金券',
  'Cafe & Dessert': '咖啡与甜点',
  'General Buffet': '自助餐',
  'General Dining': '餐饮',
  'Hotel Buffet': '酒店自助餐',
  'Hotel Dining': '酒店餐饮',
  'Others': '其他体验',
  'ATV与全轮驱动': '全地形车与越野车',
  'Airport Public Transfer': '机场公共交通',
  'Golf': '高尔夫',
  'Tea Ceremony': '茶道',
  '花园 & 公园': '花园与公园',
  '观景台 & 塔楼': '观景台与高塔',
};

const places = new Map(Object.entries(placeTranslations).map(([raw, zh]) => [normalizeName(raw), zh]));
const regions = new Map(Object.entries(countryRegions).map(([raw, iso]) => [normalizeName(raw), iso]));
const categories = new Map(Object.entries(categoryTranslations).map(([raw, zh]) => [normalizeName(raw), zh]));
const regionNames = new Intl.DisplayNames(['zh-CN'], { type: 'region' });
const isChineseLabel = (name: string) => /\p{Script=Han}/u.test(name) && !/\p{Script=Latin}/u.test(name);

/** Missing labels remain absent; future unmapped names get an honest Chinese fallback. */
export function placeNameZh(name?: string | null): string {
  if (!name?.trim()) return '';
  const value = name.trim();
  return places.get(normalizeName(value)) || (isChineseLabel(value) ? value : '当地目的地');
}

/** code accepts ISO alpha-2, not the supplier's numeric country_code. */
export function countryNameZh(name?: string | null, code?: string | null): string {
  const value = name?.trim() || '';
  if (normalizeName(value) === 'mainland china') return '中国大陆';
  if (isChineseLabel(value)) return value;
  const iso = regions.get(normalizeName(value)) || (/^[a-z]{2}$/i.test(code || '') ? code!.toUpperCase() : '');
  if (iso === 'HK') return '香港';
  if (iso === 'MO') return '澳门';
  if (iso === 'TW') return '台湾地区';
  if (iso) {
    const display = regionNames.of(iso);
    if (display && isChineseLabel(display)) return display;
  }
  return value || code ? '其他地区' : '';
}

export function categoryNameZh(name?: string | null): string {
  if (!name?.trim()) return '当地体验';
  const value = name.trim();
  return categories.get(normalizeName(value)) || (isChineseLabel(value) ? value : '其他体验');
}

export function locationLabelZh(city?: string | null, country?: string | null, countryCode?: string | null): string {
  const translated = [placeNameZh(city), countryNameZh(country, countryCode)].filter(Boolean);
  return [...new Set(translated)].join(' · ') || '当地体验';
}
